pluginManagement {
    repositories {
//        google()
        maven { url 'https://maven.aliyun.com/repository/google' }
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://mirrors.huaweicloud.com/repository/maven/' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
//        google()
        maven { url 'https://maven.aliyun.com/repository/google' }
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://mirrors.huaweicloud.com/repository/maven/' }
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name='classic-bluetooth'
include ':app'
include ':library'
